package com.orbit.util;

/**
 * Node types for HIR analysis.
 */
public enum NodeType {
    LITERAL, CHAR_CLASS, PAIR, CONCAT, UNION,
    QUANTIFIER, LAZY_QUANTIFIER, POSSESSIVE_QUANTIFIER, GROUP, ANCHOR, EPSILON, BACKREF,
    ANONYMOUS, ALTERNATIVE, CAPTURE, LOOKAHEAD,
    LOOKAHEAD_NEG, LOOKBEHIND, LOOKBEHIND_NEG,
    BACKTRACK, ACCEPT, FAIL,
    FLAG_EXPR, ATOMIC_GROUP,
    BALANCE_GROUP, CONDITIONAL,
    KEEP_ASSERTION
}